# Generated by Django 6.0.6 on 2026-06-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_datasetrequest_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrequest',
            name='min_rows',
            field=models.IntegerField(blank=True, help_text='Jumlah baris minimum (opsional)', null=True),
        ),
        migrations.AddField(
            model_name='datasetrequest',
            name='required_columns',
            field=models.TextField(blank=True, help_text='Nama kolom yang harus ada, pisahkan dengan koma (opsional)', null=True),
        ),
    ]
