# Generated by Django 6.0.4 on 2026-06-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datasetrequest_min_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrequest',
            name='ic_submission_id',
            field=models.IntegerField(blank=True, help_text='ID submission dari IC', null=True),
        ),
    ]
