# Generated by Django 6.0.6 on 2026-06-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datasetrequest_min_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrequest',
            name='fulfilled_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='core.datasetfile'),
        ),
        migrations.AddField(
            model_name='datasetrequest',
            name='ic_webhook_url',
            field=models.URLField(blank=True, help_text='URL Webhook untuk mengirimkan hasil kembali ke IC', null=True),
        ),
    ]
