version: '3.8'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_DEBUG=False
      - SECRET_KEY=ganti_dengan_key_produksi_anda
    networks:
      - django_net

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - django_net

volumes:
  static_volume:

networks:
  django_net:
    driver: bridge

